Repository AY2122S2-CS2103T-T17-4/tp, pull requests merged in 2022-04, with the labels that each got.

#234 [#201][#213] Fix minor UserGuide.md bugs
  docs/UserGuide.md
Labels: severity.Low, type.Bug

#237 [#207] Improve error message for incorrect date
  src/main/java/seedu/address/model/person/ContactedDate.java
Labels: severity.Low, type.Bug

#239 [#221] Update UserGuide.md to indicate how to remove all tags
  docs/UserGuide.md
Labels: severity.Low, type.Bug

#238 [#222][#224][#225] Revamp equals for Person and person attributes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Memo.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/MemoTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/MemoUtil.java
Labels: severity.Low, type.Bug

#242 [#241] EP comments for MemoTest, ContactedDateTest, StateAddressBookTest and ParserUtilTest
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/StateAddressBookTest.java
  src/test/java/seedu/address/model/person/ContactedDateTest.java
  src/test/java/seedu/address/model/person/MemoTest.java
  src/test/java/seedu/address/testutil/MemoUtil.java
Labels: priority.Medium, type.Task

#243 [#208][#215][#218][#223][#229][#230][#231] Fix issues from PE-D
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ScrubCommand.java
  src/test/java/seedu/address/logic/commands/ScrubCommandTest.java
Labels: severity.Low, type.Bug

#245 [#244] Improve AddTagCommand and DeleteTagCommand messages
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
Labels: severity.Low, type.Task

#249 [#200] Error message for incorrect index given
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: severity.Low, type.Bug

#252 [#251] PPP draft (Alvin Tay)
  docs/UserGuide.md
  docs/team/atmh.md
Labels: priority.Medium, type.Task

#255 [#253] Add tests to AddTag command and AddTagCommandParser class
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
Labels: priority.Medium, type.Task

#250 [#199][#204][#210][#212] Fix bugs from PE-D
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/ContactedDate.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Memo.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/ExactTagComparator.java
  src/main/java/seedu/address/ui/DetailedPersonDisplay.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DetailedPersonDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/ContactedDateTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/MemoTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Bug

#264 [#263] Revamp equality for phone numbers
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/ContactedDate.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Memo.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: severity.Low, type.Task

#266 [#265] Update Abπ logo
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/pi.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.Medium, type.Task

#268 [#259][#260][#262] Fix feature bugs in `find m/` and `find p/`
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Memo.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/predicate/ExactWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/FindPersonPredicate.java
  src/main/java/seedu/address/model/person/predicate/MemoMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/PartialWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/ScrubPersonPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/predicate/DomainMatchPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/ExactWordMatchPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/FindPersonPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/MemoMatchPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/PartialWordMatchPredicateTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/MemoUtil.java
Labels: severity.Medium, type.Bug

#267 [#257] Add implementation details for duplicate detection in DeveloperGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#270 [#269] Remove duplicated code Phone#removeAllWhiteSpace(String)
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Phone.java
Labels: priority.Medium, type.Task

#273 [#272] Update Abπ version to v1.4.ea
  src/main/java/seedu/address/MainApp.java
Labels: priority.Medium, type.Task

#275 [#274] Update UserGuide Quick Start section and improve formatting
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#276 [#271] Update PPP for tandeshao.md
  docs/team/tandeshao.md
Labels: priority.Medium, type.Task

#278 [#277] Add instructions for manual testing in DeveloperGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/atmh.md
Labels: priority.Medium, type.Task

#280 [#279] Improve invalid command message
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.Medium, type.Task

#283 [#282] Improve UG formatting, add details about max integer and chronological ordering of contacts
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#287 [#286] Update `index.md`
  docs/UserGuide.md
  docs/index.md
Labels: priority.Medium, type.Task

#285 [#284] Update `README.md`
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiGuide.png
  docs/index.md
Labels: priority.Medium, type.Task

#291 [#290] Update non-functional requirement and glossary
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#298 [#297] Add use case in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#296 [#295] Update instruction for manual testing in DeveloperGuide
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#300 [#299] Add conventions in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#302 [#301] Fix conventions table
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#304 [#303] Update PPP for tandeshao.md (DG contributions)
  docs/team/tandeshao.md
Labels: priority.Medium, type.Task

#308 adds a space to xpzmichael.md
  docs/team/xpzmichael.md
Labels: priority.Low, type.Task

#281 [#145] update DG for previous/next feature
  docs/DeveloperGuide.md
  docs/diagrams/CommandList0.puml
  docs/diagrams/CommandList1.puml
  docs/diagrams/CommandList2.puml
  docs/diagrams/CommandList3.puml
  docs/diagrams/CommandList4.puml
  docs/diagrams/CommandList5.puml
  docs/diagrams/HistoryActivityDiagram.puml
  docs/images/CommandList0.png
  docs/images/CommandList1.png
  docs/images/CommandList2.png
  docs/images/CommandList3.png
  docs/images/CommandList4.png
  docs/images/CommandList5.png
  docs/images/HistoryActivityDiagram.png
Labels: type.Story, priority.Medium

#313 [#312] Fix Delete, Edit and Undo sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditMemoSequenceDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditMemoSequenceDiagram.png
  docs/images/UndoSequenceDiagram.png
Labels: priority.Medium, type.Task

#315 [#314] Fix FindCommand Sequence Diagram in DG
  docs/DeveloperGuide.md
  docs/assets/css/style.scss
  docs/diagrams/CommandResult.puml
  docs/diagrams/FindPersonPredicate.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/CommandResult.png
  docs/images/FindPersonPredicate.png
  docs/images/FindSequenceDiagram.png
Labels: priority.Medium, type.Task

#318 [#317] Improve UserGuide for PDF conversion
  docs/UserGuide.md
  docs/backupFileImage.png
  docs/images/backupFileImage.png
Labels: priority.Medium, type.Task

#319 [#256] Add backup documentation in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: priority.Medium, type.Task

#321 [#320] Tidy up JavaDocs
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/StateAddressBook.java
Labels: priority.Medium, type.Task

#323 [#322] Fix JavaDocs documentation mistakes
  docs/DeveloperGuide.md
  docs/team/tandeshao.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ScrubCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ScrubCommandParser.java
  src/main/java/seedu/address/model/person/predicate/DomainMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/ExactWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/FindPersonPredicate.java
  src/main/java/seedu/address/model/person/predicate/PartialWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/ScrubPersonPredicate.java
Labels: priority.Medium, type.Task
