Repository AY2122S2-CS2103T-T17-4/tp, pull requests merged in 2022-03, with the labels that each got.

#40 [#39] Update UserGuide.md with copyemails
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#37 [#38] Update Project Portfolio Page for lovemathboy.md
  docs/team/lovemathboy.md
Labels: priority.Medium, type.Documentation

#43 Update UG to reflect Abπ instead of Ab3
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#47 Update addressbook.jar to abpie.jar
  docs/UserGuide.md
Labels: priority.High

#65 [#9] Add copyemails command.
  src/main/java/seedu/address/logic/commands/CopyEmailsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/CopyEmailsCommandTest.java
Labels: priority.Medium

#66 [#68] Remove CopyEmailsCommandTest.java
  src/test/java/seedu/address/logic/commands/CopyEmailsCommandTest.java
Labels: type.Bug

#81 [#80] Remove dead code (HistoryCommandException.java)
  src/main/java/seedu/address/logic/commands/exceptions/HistoryCommandException.java
Labels: severity.Low, type.Task

#77 [#75] Add tests for ArgumentMultiMap class
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/ArgumentMultimapTest.java
Labels: priority.Medium, type.Task

#86 Enable assertions
  build.gradle
Labels: priority.Medium, type.Task

#88 [#87] Add logging to AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.Medium, type.Task

#90 [#79] Improve Code Quality
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
Labels: type.Task

#94 [#59, #60] Add undo and redo command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/StateAddressBook.java
  src/main/java/seedu/address/model/exceptions/InvalidRedoException.java
  src/main/java/seedu/address/model/exceptions/InvalidUndoException.java
  src/main/java/seedu/address/model/person/Memo.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/StateAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.Medium

#96 [#95] Update memo of SampleDataUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, type.Task

#100 [#99] Update version number in MainApp.java to v1.3.0
  src/main/java/seedu/address/MainApp.java
Labels: priority.Medium, type.Task

#103 [#97] Update DeveloperGuide with FindCommand details
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/GetPersonContainsKeywordsPredicate.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonAttributeClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/GetPersonContainsKeywordsPredicate.png
  docs/images/ModelClassDiagram.png
  docs/images/PersonAttributeClassDiagram.png
Labels: type.Task

#107 [#106]Update Design Considerations in DeveloperGuide
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/person/PersonAttribute.java
Labels: documentation

#111 [#110] Update Memo validation
  src/main/java/seedu/address/model/person/Memo.java
Labels: priority.Medium, type.Task

#109 [#108] Update multiplicity of Memo in UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: priority.Medium, type.Task

#105 [#104] Refactor helper method names in StateAddressBookTest and RedoCommandTest class
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/model/StateAddressBookTest.java
Labels: severity.Low, type.Task

#118 [#112] Fix FindCommand
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPersonDescriptor.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Memo.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonAttribute.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/predicate/ExactWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/PartialWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/PersonPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentMultimapTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindPersonDescriptorTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/ExactWordMatchPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/PartialWordMatchPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/PersonPredicateTest.java
Labels: priority.Medium, type.Task

#114 [#113] Add logging and assertion to several classes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/StateAddressBook.java
  src/main/java/seedu/address/model/person/Memo.java
Labels: priority.Medium, type.Task

#121 [#120] Update empty memo logic and UI for memo
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Memo.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentMultimapTest.java
  src/test/java/seedu/address/model/person/MemoTest.java
  src/test/java/seedu/address/testutil/MemoUtil.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Task

#123 [#119] Update UserGuide and DeveloperGuide on new FindCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/GetPersonContainsKeywordsPredicate.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonPredicate.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/GetPersonContainsKeywordsPredicate.png
  docs/images/ModelClassDiagram.png
  docs/images/PersonPredicate.png
  src/main/java/seedu/address/logic/parser/FindPersonDescriptor.java
Labels: priority.Medium, type.Task

#130 [#102] Add Proof-Of-Concept DNC Scrubbing
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindPersonPredicate.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/PersonPredicate.puml
  docs/images/FindPersonPredicate.png
  docs/images/FindSequenceDiagram.png
  docs/images/PersonPredicate.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ScrubCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PersonDescriptor.java
  src/main/java/seedu/address/logic/parser/ScrubCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/predicate/DomainMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/ExactWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/FindPersonPredicate.java
  src/main/java/seedu/address/model/person/predicate/PartialWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/ScrubPersonPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ScrubCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/ScrubCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicate/DomainMatchPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/FindPersonPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/ScrubPersonPredicateTest.java
Labels: priority.Medium, type.Task

#133 [#98] Add contacted date
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/StateAddressBook.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/ContactedDate.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Memo.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/ContactedDateTest.java
  src/test/java/seedu/address/model/person/MemoTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/MemoUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.Medium

#136 Enable logging for CopyEmailsCommand
  src/main/java/seedu/address/logic/commands/CopyEmailsCommand.java
Labels: severity.Low, type.Task

#139 [#138] Replace dependency of PersonPredicate in ScrubCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindPersonPredicate.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindPersonPredicate.png
  docs/images/FindSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ScrubCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/PersonDescriptor.java
  src/main/java/seedu/address/logic/parser/ScrubCommandParser.java
  src/main/java/seedu/address/model/person/predicate/ContactedDateMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/DomainMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/ExactWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/FindPersonPredicate.java
  src/main/java/seedu/address/model/person/predicate/PartialWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/ScrubPersonPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ScrubCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/ScrubCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicate/ContactStatusMatchPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/DomainMatchPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/ExactWordMatchPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/FindPersonPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/PartialWordMatchPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/ScrubPersonPredicateTest.java
Labels: priority.Medium, type.Task

#141 [#134] Add test for ModelManager#deleteAllPerson(ObservableList<Person>)
  docs/UserGuide.md
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task

#142 [#135] Improve on tests for ContactedDateMatchPredicate
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.Medium, type.Task

#144 [#143] Update UserGuide.md and DeveloperGuide.md with ContactedDate
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/EditMemoSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/EditMemoSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/model/person/ContactedDate.java
Labels: priority.Medium, type.Task

#147 [#115] Backup corrupted save file.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
Labels: severity.High, type.Task

#150 [#116] Prevent trailing characters in AddressBookParser
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CopyEmailsCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/NextCommand.java
  src/main/java/seedu/address/logic/commands/PreviousCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: bug, severity.Medium

#152 [#151] Clean up UserGuide.md and update FAQ
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Medium, type.Task

#155 [#154] Update UG for CS2101 Submission
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiGuide.png
Labels: severity.Medium, type.Task

#157 [#156] Improve UserGuide.md formatting
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#159 [#158] Improve UserGuide.md page breaks when converted to pdf
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#161 [#160] Refine UserGuide.md page breaks when converted to PDF
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#163 [#162] Add JUnit tests for AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium, type.Task

#165 [#164] Improve DeveloperGuide.md Formatting
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#166 [#117] Limit number of characters for Name, Address, Email and Phone
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
Labels: severity.Medium, type.Bug

#168 [#167] Refine UserGuide.md content
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#171 [#170] Add AddTagCommand
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: type.Story, priority.Medium

#173 [#82] Enhance UI with a new display window
  src/main/java/seedu/address/logic/commands/CopyEmailsCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/DetailedPersonDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DetailedPersonDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#177 [#169] Change parameter for ScrubCommand to predicate instead of ArgumentMultimap
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindPersonPredicate.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindPersonPredicate.png
  docs/images/FindSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ScrubCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ScrubCommandParser.java
  src/main/java/seedu/address/model/person/predicate/ContactedDateMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/FindPersonPredicate.java
  src/main/java/seedu/address/model/person/predicate/PartialWordMatchPredicate.java
  src/main/java/seedu/address/model/person/predicate/ScrubPersonPredicate.java
  src/test/java/seedu/address/logic/commands/ScrubCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ScrubCommandParserTest.java
  src/test/java/seedu/address/model/person/predicate/FindPersonPredicateTest.java
Labels: priority.Medium, type.Task

#178 [#172] Add DeleteTagCommand
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/ContactedDate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.Medium

#180 [#179] Reformat UserGuide.md and update with DeleteTagCommand details
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#182 [#181]Update UserGuide with AddTagCommand and ScrubCommand
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/predicate/DomainMatchPredicate.java
Labels: priority.Medium, type.Task

#184 [#183] Update Person#toString()
  src/main/java/seedu/address/model/person/Person.java
Labels: severity.Medium, type.Bug

#190 [#189] Update UG with view command
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#174 [#174][#176] Limit tag size and Change name to allow all characters
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: severity.Medium, type.Bug

#192 [#191] Update Find Command to allow stricter search conditions
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ScrubCommandParser.java
  src/main/java/seedu/address/model/person/predicate/FindPersonPredicate.java
  src/main/java/seedu/address/model/person/predicate/ScrubPersonPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/predicate/FindPersonPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/ScrubPersonPredicateTest.java
Labels: priority.Medium, type.Task

#194 [193] Update version to v1.3.1
  src/main/java/seedu/address/MainApp.java
Labels: priority.Medium, type.Task

#196 [#195] Update documentation on ScrubCommand
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#198 [#197] Update UG with new UI images
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiGuide.png
  docs/images/ug/Ui.png
  docs/images/ug/UiGuide.png
  docs/index.md
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
Labels: priority.High, type.Bug
